#!/bin/sh

feh --bg-scale ~/Pictures/wallpaper.jpg &
picom --config /home/mrk/.config/picom/picom.conf &
xbindkeys --poll-rc &
polybar main &

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
