set path+=**

set wildmode=longest,list,full
set wildmenu

set wildignore+=*./vendor/*

set relativenumber 
set number
set nohlsearch
set hidden
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent

set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile

set incsearch
set syntax
set termguicolors
set scrolloff=5
set signcolumn=yes
set isfname+=@-@

set mouse=a

set cmdheight=1

set updatetime=50
set shortmess+=c


call plug#begin('~/.vim/plugged')

Plug 'gruvbox-community/gruvbox'

call plug#end()

colorscheme gruvbox


let mapleader = " "
