#! /bin/sh

transmission-qt &
pidgin &
sxhkd &
$HOME/.config/polybar/launch.sh &

# second_monitor=$(xrandr --query | grep 'DVI-D-0')
# if [[ second_monitor = *connected* ]]; then
#   xrandr --output DisplayPort-0 --primary --output DVI-D-0 --rotate left --right-of DisplayPort-0
# fi

# bspc monitor DisplayPort-0 -n 0 -d todo web 3 4 5 6
# bspc monitor DVI-I-1 -n 1 -d term web 3 4 5 6 7 8 chat music
 bspc monitor DisplayPort-0 -n 1 -d term web 3 4 5 6 7 8 chat music

bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config focus_follows_pointer false

bspc config pointer_modifier mod1
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action1 move

bspc rule -a Pidgin desktop='^9' state=floating
bspc rule -a transmission-qt desktop='^8' state=floating
bspc rule -a com.spotify.Client desktop='^10' state=floating follow=on
bspc rule -a Screenkey manage=off

bpadding_top=0
padding_bottom=0
padding_left=0
padding_right=0

color_normal_border="#666666"
color_active_border="#666666"
color_focused_border="#cccccc"
color_presel_feedback="#888888"

setting_borderless_monocle='false'

# polybar_config="$CURRENT_THEME/polybar"
polybar_bars=(main)

# if xrandr | grep -q "HDMI-1 connected"; then
#   polybar_bars+=(main)
# fi
