#!/usr/bin/env sh

choice="$(echo "alacritty\nbspwm\ndunst\nfirefox\nneovim\npicom\npolybar\nspotifyd\nst\nsxhkd\nxob\nzsh" | dmenu -i -p "config files:  ")"

if [ "$choice" = "alacritty" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/alacritty/alacritty.yml
elif [ "$choice" = "bspwm" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/bspwm/bspwmrc
elif [ "$choice" = "dunst" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/dunst/dunstrc
elif [ "$choice" = "firefox" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/firefox/userChrome.css
elif [ "$choice" = "neovim" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/nvim/init.vim
elif [ "$choice" = "picom" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/picom/picom.conf
elif [ "$choice" = "polybar" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/polybar/config.ini
elif [ "$choice" = "spotifyd" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/spotifyd/spotifyd.conf
elif [ "$choice" = "st" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/st/config.h
elif [ "$choice" = "sxhkd" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/sxhkd/sxhkdrc
elif [ "$choice" = "xob" ]; then
    $TERMINAL -e $EDITOR $HOME/.config/xob/styles.cfg
elif [ "$choice" = "zsh" ]; then
    $TERMINAL -e $EDITOR $HOME/.zshrc
fi
