#!/usr/bin/env sh

choice="$(echo "screen\nselect\nfocused" | dmenu -i -p "screenshot menu:  ")"

if [ "$choice" = "screen" ]; then
    sleep 0.5s && scrot '%Y-%m-%d_%H-%M-%S_$wx$h_scrot.png' -e 'mv $f ~/photos/screenshots/'
elif [ "$choice" = "select" ]; then
    scrot --select '%Y-%m-%d_$wx$h_scrot.png' -e 'mv $f ~/photos/screenshots/'
elif [ "$choice" = "focused" ]; then
    scrot --focused '%Y-%m-%d_$wx$h_scrot.png' -e 'mv $f ~/photos/screenshots/'
fi
