#!/usr/bin/env sh

choice="$(echo "lock\nlogout\nsuspend\nhibernate\nreboot\nshutdown" | dmenu -i -p "system menu:  ")"

case "$choice" in
    "logout")
        $SCRIPTS/dmenu/prompt "logout?" "bspc quit"
        break
        ;;
    "suspend")
        systemctl suspend
        break
        ;;
    "hibernate")
        systemctl hibernate
        break
        ;;
    "reboot")
        $SCRIPTS/dmenu/prompt "reboot?" "systemctl reboot"
        break
        ;;
    "shutdown")
        $SCRIPTS/dmenu/prompt "shutdown?" "systemctl poweroff"
        break
        ;;
esac
